FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /workspace

COPY requirements-app.txt .
RUN pip install --no-cache-dir -r requirements-app.txt

COPY app ./app
COPY inventory_service ./inventory_service

EXPOSE 8001

CMD ["uvicorn", "inventory_service.main:app", "--host", "0.0.0.0", "--port", "8001"]
