FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /workspace

COPY requirements-app.txt .
RUN pip install --no-cache-dir -r requirements-app.txt

COPY app ./app
COPY orders_service ./orders_service

EXPOSE 8002

CMD ["uvicorn", "orders_service.main:app", "--host", "0.0.0.0", "--port", "8002"]
