server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /health {
        default_type application/json;
        return 200 '{"status":"ok","service":"web"}';
    }

    location /gateway/core/ {
        proxy_pass http://api:8000/api/v1/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /gateway/inventory/ {
        proxy_pass http://inventory-api:8001/api/v1/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /gateway/orders/ {
        proxy_pass http://orders-api:8002/api/v1/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
